# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jenkins/Documents/GTestSample

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jenkins/Documents/GTestSample

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jenkins/Documents/GTestSample/CMakeFiles /home/jenkins/Documents/GTestSample/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jenkins/Documents/GTestSample/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ParameterizedTestExamples

# Build rule for target.
ParameterizedTestExamples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParameterizedTestExamples
.PHONY : ParameterizedTestExamples

# fast build rule for target.
ParameterizedTestExamples/fast:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/build
.PHONY : ParameterizedTestExamples/fast

src/LeapYear.o: src/LeapYear.cpp.o

.PHONY : src/LeapYear.o

# target to build an object file
src/LeapYear.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/src/LeapYear.cpp.o
.PHONY : src/LeapYear.cpp.o

src/LeapYear.i: src/LeapYear.cpp.i

.PHONY : src/LeapYear.i

# target to preprocess a source file
src/LeapYear.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/src/LeapYear.cpp.i
.PHONY : src/LeapYear.cpp.i

src/LeapYear.s: src/LeapYear.cpp.s

.PHONY : src/LeapYear.s

# target to generate assembly for a file
src/LeapYear.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/src/LeapYear.cpp.s
.PHONY : src/LeapYear.cpp.s

test/LeapYearFixtureCombinedWithParameterizedTests.o: test/LeapYearFixtureCombinedWithParameterizedTests.cpp.o

.PHONY : test/LeapYearFixtureCombinedWithParameterizedTests.o

# target to build an object file
test/LeapYearFixtureCombinedWithParameterizedTests.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearFixtureCombinedWithParameterizedTests.cpp.o
.PHONY : test/LeapYearFixtureCombinedWithParameterizedTests.cpp.o

test/LeapYearFixtureCombinedWithParameterizedTests.i: test/LeapYearFixtureCombinedWithParameterizedTests.cpp.i

.PHONY : test/LeapYearFixtureCombinedWithParameterizedTests.i

# target to preprocess a source file
test/LeapYearFixtureCombinedWithParameterizedTests.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearFixtureCombinedWithParameterizedTests.cpp.i
.PHONY : test/LeapYearFixtureCombinedWithParameterizedTests.cpp.i

test/LeapYearFixtureCombinedWithParameterizedTests.s: test/LeapYearFixtureCombinedWithParameterizedTests.cpp.s

.PHONY : test/LeapYearFixtureCombinedWithParameterizedTests.s

# target to generate assembly for a file
test/LeapYearFixtureCombinedWithParameterizedTests.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearFixtureCombinedWithParameterizedTests.cpp.s
.PHONY : test/LeapYearFixtureCombinedWithParameterizedTests.cpp.s

test/LeapYearFixtureTests.o: test/LeapYearFixtureTests.cpp.o

.PHONY : test/LeapYearFixtureTests.o

# target to build an object file
test/LeapYearFixtureTests.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearFixtureTests.cpp.o
.PHONY : test/LeapYearFixtureTests.cpp.o

test/LeapYearFixtureTests.i: test/LeapYearFixtureTests.cpp.i

.PHONY : test/LeapYearFixtureTests.i

# target to preprocess a source file
test/LeapYearFixtureTests.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearFixtureTests.cpp.i
.PHONY : test/LeapYearFixtureTests.cpp.i

test/LeapYearFixtureTests.s: test/LeapYearFixtureTests.cpp.s

.PHONY : test/LeapYearFixtureTests.s

# target to generate assembly for a file
test/LeapYearFixtureTests.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearFixtureTests.cpp.s
.PHONY : test/LeapYearFixtureTests.cpp.s

test/LeapYearIterationTest.o: test/LeapYearIterationTest.cpp.o

.PHONY : test/LeapYearIterationTest.o

# target to build an object file
test/LeapYearIterationTest.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearIterationTest.cpp.o
.PHONY : test/LeapYearIterationTest.cpp.o

test/LeapYearIterationTest.i: test/LeapYearIterationTest.cpp.i

.PHONY : test/LeapYearIterationTest.i

# target to preprocess a source file
test/LeapYearIterationTest.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearIterationTest.cpp.i
.PHONY : test/LeapYearIterationTest.cpp.i

test/LeapYearIterationTest.s: test/LeapYearIterationTest.cpp.s

.PHONY : test/LeapYearIterationTest.s

# target to generate assembly for a file
test/LeapYearIterationTest.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearIterationTest.cpp.s
.PHONY : test/LeapYearIterationTest.cpp.s

test/LeapYearMultipleParametersTests.o: test/LeapYearMultipleParametersTests.cpp.o

.PHONY : test/LeapYearMultipleParametersTests.o

# target to build an object file
test/LeapYearMultipleParametersTests.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearMultipleParametersTests.cpp.o
.PHONY : test/LeapYearMultipleParametersTests.cpp.o

test/LeapYearMultipleParametersTests.i: test/LeapYearMultipleParametersTests.cpp.i

.PHONY : test/LeapYearMultipleParametersTests.i

# target to preprocess a source file
test/LeapYearMultipleParametersTests.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearMultipleParametersTests.cpp.i
.PHONY : test/LeapYearMultipleParametersTests.cpp.i

test/LeapYearMultipleParametersTests.s: test/LeapYearMultipleParametersTests.cpp.s

.PHONY : test/LeapYearMultipleParametersTests.s

# target to generate assembly for a file
test/LeapYearMultipleParametersTests.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearMultipleParametersTests.cpp.s
.PHONY : test/LeapYearMultipleParametersTests.cpp.s

test/LeapYearParameterizedTestFixture.o: test/LeapYearParameterizedTestFixture.cpp.o

.PHONY : test/LeapYearParameterizedTestFixture.o

# target to build an object file
test/LeapYearParameterizedTestFixture.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearParameterizedTestFixture.cpp.o
.PHONY : test/LeapYearParameterizedTestFixture.cpp.o

test/LeapYearParameterizedTestFixture.i: test/LeapYearParameterizedTestFixture.cpp.i

.PHONY : test/LeapYearParameterizedTestFixture.i

# target to preprocess a source file
test/LeapYearParameterizedTestFixture.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearParameterizedTestFixture.cpp.i
.PHONY : test/LeapYearParameterizedTestFixture.cpp.i

test/LeapYearParameterizedTestFixture.s: test/LeapYearParameterizedTestFixture.cpp.s

.PHONY : test/LeapYearParameterizedTestFixture.s

# target to generate assembly for a file
test/LeapYearParameterizedTestFixture.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearParameterizedTestFixture.cpp.s
.PHONY : test/LeapYearParameterizedTestFixture.cpp.s

test/LeapYearStandaloneTests.o: test/LeapYearStandaloneTests.cpp.o

.PHONY : test/LeapYearStandaloneTests.o

# target to build an object file
test/LeapYearStandaloneTests.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearStandaloneTests.cpp.o
.PHONY : test/LeapYearStandaloneTests.cpp.o

test/LeapYearStandaloneTests.i: test/LeapYearStandaloneTests.cpp.i

.PHONY : test/LeapYearStandaloneTests.i

# target to preprocess a source file
test/LeapYearStandaloneTests.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearStandaloneTests.cpp.i
.PHONY : test/LeapYearStandaloneTests.cpp.i

test/LeapYearStandaloneTests.s: test/LeapYearStandaloneTests.cpp.s

.PHONY : test/LeapYearStandaloneTests.s

# target to generate assembly for a file
test/LeapYearStandaloneTests.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/LeapYearStandaloneTests.cpp.s
.PHONY : test/LeapYearStandaloneTests.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/ParameterizedTestExamples.dir/build.make CMakeFiles/ParameterizedTestExamples.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ParameterizedTestExamples"
	@echo "... test"
	@echo "... src/LeapYear.o"
	@echo "... src/LeapYear.i"
	@echo "... src/LeapYear.s"
	@echo "... test/LeapYearFixtureCombinedWithParameterizedTests.o"
	@echo "... test/LeapYearFixtureCombinedWithParameterizedTests.i"
	@echo "... test/LeapYearFixtureCombinedWithParameterizedTests.s"
	@echo "... test/LeapYearFixtureTests.o"
	@echo "... test/LeapYearFixtureTests.i"
	@echo "... test/LeapYearFixtureTests.s"
	@echo "... test/LeapYearIterationTest.o"
	@echo "... test/LeapYearIterationTest.i"
	@echo "... test/LeapYearIterationTest.s"
	@echo "... test/LeapYearMultipleParametersTests.o"
	@echo "... test/LeapYearMultipleParametersTests.i"
	@echo "... test/LeapYearMultipleParametersTests.s"
	@echo "... test/LeapYearParameterizedTestFixture.o"
	@echo "... test/LeapYearParameterizedTestFixture.i"
	@echo "... test/LeapYearParameterizedTestFixture.s"
	@echo "... test/LeapYearStandaloneTests.o"
	@echo "... test/LeapYearStandaloneTests.i"
	@echo "... test/LeapYearStandaloneTests.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

